stages:
  - setup
  - build
  - deploy
  - restartFE

setup_job:
  stage: setup
  script:
    - npm config set strict-ssl false
    - npm config set registry "https://registry.npm.taobao.org/"
    - npm install
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
  artifacts:
    when: always
    paths:
      - node_modules/*
    expire_in: "1 week"
  tags:
    - test

build_job:
  stage: build
  script:
    - sed -i -re "s/(^\s*config\.host)\s*=.*/\1='api\.szdev\.cn'/" src/server/config_master.js
    - npm run buildP
  artifacts:
    when: always
    paths:
      - build/*
    expire_in: "1 week"
  tags:
    - test

deploy_to_67_job:
  stage: deploy
  script:
    - proj_path="/home/ump/UMP/$CI_BUILD_REF_NAME/ump"
    - function at_67 { ssh ump@10.0.15.67 $1; }
    - at_67 "mkdir -p ${proj_path}-manager/build ${proj_path}-manager/node_modules"
    - scp -r build/* ump@10.0.15.67:"${proj_path}-manager/build"
    - scp -r node_modules/* ump@10.0.15.67:"${proj_path}-manager/node_modules"
    - at_67 "sed -i -re \"s/(^\s*config\.host)\s*=.*/\1='api\.szdev\.cn'/\" ${proj_path}-manager/build/config_master.js"
    - at_67 "killall -q node; nohup node ${proj_path}-manager/build/server.js >/dev/null 2>&1 &"

  environment:
    name: test
  tags:
    - test
  only:
    - dev


restart_to_68_job:
  stage: restartFE
  script:
    - proj_path="/home/gitlab-runner/"
    - cp -r build/api ${proj_path}UMP-FE/src/fe
    - killall -q node
    - cd ${proj_path}UMP-FE
    - npm run build
    - cd dist
    - nohup node server.js >/dev/null 2>&1 &
  tags:
    - test
  only:
    - dev
